### PR TITLE
Make DinoPark more like NLX (DP-1337)

### PR DESCRIPTION
**Pull request by hidde**
Adds two things:

* blue line hover on inputs, textareas, custom selects
* blue line hover on search results

### CODE REVIEW

**Comment by jens1o** [comment]
What's NLX?

**Comment by hidde** [comment]
@jens1o NLX is short for ‘New Login Experience’,  it is basically the login screen you see when using Mozilla IAM/SSO.

**Comment by jens1o** [comment]
Is this already the new one or is there going to be a new one, soon?

**Comment by hidde** [comment]
It's been around for about a year.

**Pull request merged**
